system:
  port: 9044
  bk_port: 9045
  debug: true
  log_path: zap.conf
  monitor: :21001

redis:
  network: tcp
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  maxIdle: 0
  maxActive: 10
  idleTimeout: 5
  maxOpen: 200
  prefix: ""

bussiness_limits:
  phone_sms: [3-M, 30-H]  #从左到右依次匹配
  ip_sms: [100-M, 10000-H]  #从左到右依次匹配

bas_notify:
  addr: http://127.0.0.1:9100
  verifycode_sms_tmp: verifycode


mysql: #多个数据库
  host: 127.0.0.1
  port: 3306
  dbname: phonecard
  user: root
  password:
  charset: utf8
  parseTime: false
  maxIdle: 0
  maxOpen: 30
  debug: false

#https://market.aliyun.com/products/57000002/cmapi025518.html?spm=5176.730006-56956004-57126001-cmapi025189.recommend.15.b11d4cc2Hi3pvr&innerSource=detailRecommend#sku=yuncode1951800003
idcard_check:
  appcode:

cache:
  activity_max_key: 100
  activity_timeout: 3600
  sponsor_activity_max_key: 100
  sponsor_activity_timeout: 3600
  sponsor_max_key: 100
  sponsor_timeout: 10000
  page_max_key:     100
  page_timeout:     86400
  shareinfo_max_key:  100
  shareinfo_timeout:  86400
  robber_max_key: 20000
  robber_timeout: 600

marketing_main:
  fission_pack_addr: https://test-share.bastionpay.io/active/fish_active
  luckdraw_pack_addr: https://test-share.bastionpay.io/active/fish_active_voucher
aliyun:
  oss_endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucket_name: